dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: hera-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.61
- name: hera-project
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.123
- name: mqttserver
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.27
- name: nike
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.35
- name: priluxswiftlibrary
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.31
- name: priluxwebui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.185
