dependencies:
- name: ddsqa
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: europa-front
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.23
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: hera-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.61
- name: hera-project
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.124
- name: mqttserver
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: nike
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.35
- name: priluxswiftlibrary
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.41
- name: priluxwebui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.210
